import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import { RightSidebar } from '@/components/right-sidebar/right-sidebar';

import { MobileNav } from '@/components/mobile-nav';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <div className="max-w-5xl xl:max-w-7xl mx-auto flex items-start lg:px-4">
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <div className="flex w-full gap-4 items-start min-h-screen">
                <main className="border-x w-full h-full max-w-150 mx-auto lg:mx-0">
                  {children}
                  <MobileNav />
                </main>
                <div className="hidden lg:block">
                  <RightSidebar />
                </div>
              </div>
            </SidebarInset>
          </SidebarProvider>
        </div>
      </body>
    </html>
  );
}
