import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { AppSidebar } from '@/components/app-sidebar';
import { RightSidebar } from '@/components/right-sidebar';

import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from '@/components/ui/sidebar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* add dark class for temporary dark mode */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <div className="max-w-7xl mx-auto border flex h-screen">
          <SidebarProvider className="">
            <AppSidebar />
            <SidebarInset>
              <div className="flex min-h-screen gap-4">
                <main className="border-r w-full max-w-xl">{children}</main>
                {/* <div className="w-full max-w-sm bg-gray-400 hidden lg:block"></div> */}
                <RightSidebar />
              </div>
            </SidebarInset>
          </SidebarProvider>
        </div>
      </body>
    </html>
  );
}
