import { argon2, randomBytes, timingSafeEqual, type Argon2Algorithm } from 'node:crypto';
import { promisify } from 'node:util';
import * as jose from 'jose';
import { config } from '#/config/config.js';
import { logger } from '#/lib/utils/logger.js';
import { type UserDocument, USER_STATUS } from '#/modules/user/user.model.js';
import { ForbiddenError } from '#/lib/utils/error.handler.js';
import { RESPONSE_KEYS } from '@repo/shared';

const argon2Async = promisify(argon2);

const BASE64_PAD_REGEX = /=+$/;
const ARGON2_PARAMS_REGEX = /m=(\d+),t=(\d+),p=(\d+)/;

const argon2Config = config.auth.argon2;
const jwtConfig = config.auth.jwt;

const BOUNDS = {
  MIN_MEMORY: 8 * 1024, // 8 MB
  MAX_MEMORY: 128 * 1024, // 128 MB
  MAX_PASSES: 10,
  MAX_PARALLELISM: 4,
} as const;

const { MIN_MEMORY, MAX_MEMORY, MAX_PASSES, MAX_PARALLELISM } = BOUNDS;

const SUPPORTED_ALGORITHMS = ['argon2id', 'argon2i', 'argon2d'] as const;

/**
 * Type guard to check if a given string is a supported Argon2 algorithm
 * @param value - The string to check
 * @returns True if the value is a supported algorithm, false otherwise
 */

const isArgon2Algorithm = (value: string): value is Argon2Algorithm => {
  return (SUPPORTED_ALGORITHMS as readonly string[]).includes(value);
};

/**
 * Hash a plaintext password using Argon2id
 * @param password - The plaintext password to hash
 * @returns A string containing the nonce and hash, separated by a colon
 */

export const hashPassword = async (password: string): Promise<string> => {
  const nonce = randomBytes(16);

  const derivedKey = await argon2Async(argon2Config.algorithm, {
    message: password,
    nonce,
    parallelism: argon2Config.parallelism,
    memory: argon2Config.memory,
    passes: argon2Config.passes,
    tagLength: argon2Config.tagLength,
  });

  const nonceB64 = nonce.toString('base64').replace(BASE64_PAD_REGEX, '');
  const hashB64 = derivedKey.toString('base64').replace(BASE64_PAD_REGEX, '');

  return `$${argon2Config.algorithm}$v=${argon2Config.version}$m=${argon2Config.memory},t=${argon2Config.passes},p=${argon2Config.parallelism}$${nonceB64}$${hashB64}`;
};

/** Compare a plaintext password with a stored hash
 * @param password - The plaintext password to verify
 * @param storedHash - The stored hash in the format generated by hashPassword
 * @returns A boolean indicating if the password matches the hash
 */

export const comparePassword = async (password: string, storedHash: string): Promise<boolean> => {
  try {
    const parts = storedHash.split('$');

    // Format: ["", "argon2id", "v=19", "m=16384...", "nonce", "hash"] -> Length: 6
    if (parts.length !== 6) {
      logger.warn('Invalid hash format or unsupported algorithm');
      return false;
    }

    const [_, algorithm, _version, params, nonceB64, hashB64] = parts;

    if (!isArgon2Algorithm(algorithm)) {
      logger.warn(`Unsupported hashing algorithm: ${algorithm}`);
      return false;
    }

    const paramMatch = ARGON2_PARAMS_REGEX.exec(params);
    if (!paramMatch) {
      logger.warn('Invalid hash parameters format');
      return false;
    }

    const [, memory, passes, parallelism] = paramMatch.map(Number);

    if (
      memory < MIN_MEMORY ||
      memory > MAX_MEMORY ||
      passes < 1 ||
      passes > MAX_PASSES ||
      parallelism < 1 ||
      parallelism > MAX_PARALLELISM
    ) {
      logger.warn('Hash parameters are out of acceptable bounds');
      return false;
    }

    const nonce = Buffer.from(nonceB64, 'base64');
    const originalHash = Buffer.from(hashB64, 'base64');

    const derivedKey = await argon2Async(algorithm, {
      message: password,
      nonce,
      memory,
      passes,
      parallelism,
      tagLength: originalHash.length,
    });

    return timingSafeEqual(originalHash, derivedKey);
  } catch (error) {
    const errMsg = error instanceof Error ? error.message : String(error);
    logger.error(`Error comparing password: ${errMsg}`);
    return false;
  }
};

/** Check if a stored hash needs rehashing based on current Argon2 parameters
 * @param storedHash - The stored hash to check
 * @returns A boolean indicating if the hash needs to be rehashed
 */

export const checkNeedsRehash = (storedHash: string): boolean => {
  try {
    const parts = storedHash.split('$');

    // If the hash format is invalid or uses an unsupported algorithm, we should rehash
    if (parts.length !== 6 || parts[1] !== argon2Config.algorithm) {
      logger.warn('Invalid hash format or unsupported algorithm for rehash check');
      return true;
    }

    const [, algorithm, version, params] = parts;

    const currentAlgorithm = argon2Config.algorithm;
    const currentVersion = `v=${argon2Config.version}`;
    const currentParams = `m=${argon2Config.memory},t=${argon2Config.passes},p=${argon2Config.parallelism}`;

    return algorithm !== currentAlgorithm || version !== currentVersion || params !== currentParams;
  } catch (error) {
    const errMsg = error instanceof Error ? error.message : String(error);
    logger.error(`Error checking if hash needs rehash: ${errMsg}`);
    return true; // If there's an error parsing the hash, assume it needs rehashing
  }
};

// JWT Generation and Verification

const JWT_SECRET = new TextEncoder().encode(jwtConfig.secret);

/**
 * Generate a JWT token for a user * @param userId - The user's unique identifier
 * @param username - The user's username
 * @returns A signed JWT token as a string
 */

export const generateAuthToken = async (
  userId: string,
  username: string,
  // tokenVersion: number
): Promise<string> => {
  const token = await new jose.SignJWT({
    username,
    // tokenVersion,
  })
    .setProtectedHeader({ alg: 'HS256' })
    .setSubject(userId)
    .setIssuedAt()
    .setExpirationTime(jwtConfig.expiresIn)
    .sign(JWT_SECRET);

  return token;
};

/**
 * Verify a JWT token and return its payload
 * @param token - The JWT token to verify
 * @returns The payload of the token if valid, otherwise throws an error
 */

export const verifyAuthToken = async (token: string) => {
  const { payload } = await jose.jwtVerify(token, JWT_SECRET);
  return payload;
};

/**
 * Sanitize a user object by removing sensitive fields before sending it in a response
 * @param user - The user document to sanitize
 * @returns A sanitized user object with sensitive fields removed
 */

export const sanitizeUser = (user: UserDocument) => {
  const cleanUser = user && typeof user.toObject === 'function' ? user.toObject() : user;

  const {
    password: _password,
    emailVerificationToken: _emailVerificationToken,
    emailVerificationExpires: _emailVerificationExpires,
    passwordResetToken: _passwordResetToken,
    passwordResetExpires: _passwordResetExpires,
    __v: _v,
    ...safeUser
  } = cleanUser;

  return safeUser;
};

/**
 * Check if a cooldown period has passed since the last action
 * @param lastSentAt - The date when the action was last performed
 * @param cooldownTime - The cooldown duration in milliseconds
 * @returns A boolean indicating if the cooldown period is still active
 */

export const isInCooldown = (
  lastSentAt: Date | null | undefined,
  cooldownTime: number,
): boolean => {
  if (!lastSentAt) return false;
  return Date.now() - lastSentAt.getTime() < cooldownTime;
};

/** * Check a user's account status and throw appropriate errors if the account is not active
 * @param status - The user's account status
 * @param email - The user's email (optional, used for error messages)
 * @throws ForbiddenError if the account is suspended or pending verification
 */

export const checkUserStatus = (status: string, email?: string) => {
  if (status === USER_STATUS.SUSPENDED) {
    throw new ForbiddenError(RESPONSE_KEYS.ERROR.AUTH.ACCOUNT_SUSPENDED);
  }

  if (status === USER_STATUS.PENDING) {
    throw new ForbiddenError(RESPONSE_KEYS.ERROR.AUTH.EMAIL_NOT_VERIFIED, {
      email: email,
    });
  }
};
